#! /bin/bash

trap "rm -f .git/tags.$$" EXIT
# ctags --languages=ruby --tag-relative --exclude=.git -Rf tags.$$ 2>/dev/null
ctags --languages=ruby,javascript,elixir,python --exclude=.git --exclude=node_modules --exclude=bower_components -Rf tags.$$ 2>/dev/null
mv tags.$$ tags

