#!/bin/bash

function ensure_link {
  test -e "$2"
  if [[ $? == 0 ]]
  then
    mv $1 "$1.orig"
  fi
  test -L "$2" || ln -s "$1" "$2"
}

cd $HOME/scripts

ensure_link "${PWD}/.bashrc" "$HOME/.bashrc"
ensure_link "${PWD}/.vimrc" "$HOME/.vimrc"
ensure_link "${PWD}/.vim" "$HOME/.vim"
ensure_link "${PWD}/.ackrc" "$HOME/.ackrc"
ensure_link "${PWD}/.gitconfig" "$HOME/.gitconfig"
ensure_link "${PWD}/.gitignore" "$HOME/.gitignore"

if [ -d $HOME/scripts_noths ]
then
  cp $HOME/scripts_noths/noths_ed.ssh_key $HOME/.ssh/noths_ed
fi

git submodule init
git submodule update

