#!/bin/bash
# NOTE: Run this from the directory this file is in

function ensure_link {
  test -e "$2"
  if [[ $? == 0 ]]
  then
    # TODO: There's a bug where this should back up the original, but it copies
    # it to the PWD rather than the HOME folder, and then just fails to symlink
    # it...
    mv $2 "$2.orig"
  fi
  test -L "$2" || ln -s "$1" "$2"
}

cd $HOME/scripts

ensure_link "${PWD}/bashrc" "$HOME/.bashrc"
ensure_link "${PWD}/vimrc" "$HOME/.vimrc"
ensure_link "${PWD}/.vim" "$HOME/.vim"
ensure_link "${PWD}/ackrc" "$HOME/.ackrc"
ensure_link "${PWD}/gitconfig" "$HOME/.gitconfig"
ensure_link "${PWD}/gitignore_global" "$HOME/.gitignore_global"
ensure_link "${PWD}/iex.exs" "$HOME/.iex.exs"
ensure_link "${PWD}/ctags" "$HOME/.ctags"

# Needed for neovim setup
ln -s ~/.vim ~/.config/nvim

git submodule init
git submodule update

